//GENERAL STATE
export const ERRORS = "ERRORS";
//export const LOADING = "LOADING";

//TYPES PROGRAMS
export const GET_PROGRAMS = "GET_PROGRAMS";
export const GET_PROGRAM = "GET_PROGRAM";
export const ADD_PROGRAMS = "ADD_PROGRAMS";
export const UPDATE_PROGRAMS = "UPDATE_PROGRAMS";
export const DELETE_PROGRAMS = "DELETE_PROGRAMS";
export const ERROR_PROGRAMS = "ERROR_PROGRAMS";
export const LOADING = "LOADING";
export const CHECK_COMPLETE = "CHECK_COMPLETE";
export const CURRENT = "CURRENT";
//TYPES AUTH
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROGRAMS = " CLEAR_PROGRAMS";
//TYPES EXCERCISE

export const GET_EXCERCISES = "GET_EXCERCISES";
export const ADD_EXCERCISES = "ADD_EXCERCISES";
export const UPDATE_EXCERCISES = "GET_EXCERCISES";
export const SHOW_EXCERCISES = "GET_EXCERCISES";
export const DELETE_EXCERCISES = "GET_EXCERCISES";
